name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: debian-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Nix Develop Action
        uses: nicknovitski/nix-develop@v1.1.0
      - run: flutter build apk --release
      - run: echo "Done"
