name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Nix
        uses: cachix/install-nix-action@v26
        with:
          nix_path: nixpkgs=channel:nixos-23.11

      - name: Nix Develop Action
        uses: nicknovitski/nix-develop@v1.1.0
        with:
          arguments: "--impure --accept-flake-config"
      - run: flutter build apk --release

      - name: Move files to artifacts directory
        run: |
          mkdir -p artifacts
          mv build/app/outputs/flutter-apk/app-release.apk* artifacts/

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: ./artifacts
      - run: echo "Done"
