name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Nix
        uses: cachix/install-nix-action@v26

      - name: Nix Develop Action
        uses: nicknovitski/nix-develop@v1.1.0
        with:
          arguments: "--impure --accept-flake-config"
      - run: flutter build apk --release
      - run: echo "Done"
